### ISSUE TITLE
UTM-метки

### ISSUE THREAD

**Issue by ADMiNZ** [sergeytolkachyov/wt_jshopping_b24_pro#1]
Здравствуйте. Как проверить почему нет UTM-метки у заказов? Во всех заказах - UTM-метки: отсутствуют

**Comment by sergeytolkachyov** [comment]
А внешние ссылки (в рекламных системах, в соц. сетях) размечены метками? В настройках плагина в секции про utm указан примерный URL с utm. Скопируйте, замените домен на свой и протестируйте. Определение utm  меток идет с помощью JavaScript, он пока что зависит от jquery. Посмотрите в консоли браузера ошибки. Так же туда логгируются найденные utm, если не найдены - пишется название метки и null. Если такого не происходит - проблема в подключении скриптов или их порядке.
