### ISSUE TITLE
Ошибка при не продленной подписке

### ISSUE THREAD

**Issue by ADMiNZ** [sergeytolkachyov/wt_jshopping_b24_pro#2]
Забыли продлить подписку на Bitrix 24 и перестали проходить заказы с интернет магазина.

На последнем шаге заказа ошибка

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3

**Comment by sergeytolkachyov** [comment]
Заказ создается при этом в джумшоппинге?

**Comment by ADMiNZ** [comment]
Сами заказы создались - но писем ни администратору ни клиентов - нет. Так же при обновлении страницы - создавался заказ повторно (хотя выводил ошибку клиенту)

**Comment by sergeytolkachyov** [comment]
@ADMiNZ, проверьте.

**Comment by sergeytolkachyov** [comment]
@ADMiNZ версия 2.5.2. Обновитесь, пожалуйста. Если что-то не работает - пишите сюда.

**Comment by ADMiNZ** [comment]
Спасибо!
